name: openagri_app
description: OpenAgri Login Application with MVVM Pattern
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  # State Management
  provider: ^6.1.1

  # UI Components
  dio: ^5.9.0
  flutter_map: ^8.2.2
  geolocator: ^14.0.2

  # HTTP Client (for API calls)
  http: ^1.1.2
  
  # Image Picker (for Plant Health feature)
  image_picker: ^1.0.4

  # Authentication (Optional - for future implementation)
  # firebase_auth: ^4.15.3
  # google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
#    - assets/fonts/

# fonts:
#   - family: Roboto
#     fonts:
#       - asset: assets/fonts/Roboto-Regular.ttf
#       - asset: assets/fonts/Roboto-Bold.ttf
#         weight: 700
