name: openagri_app
description: OpenAgri Login Application with MVVM Pattern
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  # State Management
  provider: ^6.1.1

  # UI Components
  dio: ^5.9.0
  flutter_map: ^8.2.2
  geolocator: ^14.0.2

  # HTTP Client (for API calls)
  http: ^1.1.2

  # Image Picker (for Plant Health feature)
  image_picker: ^1.0.4
  shared_preferences: ^2.5.3
  http_parser: ^4.1.2

  # Authentication (Optional - for future implementation)
  # firebase_auth: ^4.15.3
  # google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/OpenAgri.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/image/OpenAgri.png"
  web:
    generate: true
    image_path: "assets/image/OpenAgri.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/image/OpenAgri.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/image/OpenAgri.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
#    - assets/fonts/

# fonts:
#   - family: Roboto
#     fonts:
#       - asset: assets/fonts/Roboto-Regular.ttf
#       - asset: assets/fonts/Roboto-Bold.ttf
#         weight: 700
